202MobileServiceFour/202MobileServiceFour_Web/Controllers/AppsController.cs
using _202MobileServiceFour_Core;
using _202MobileServiceFour_Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace _202MobileServiceFour_Web.Controllers
{
    [Authorize]
    public class AppsController : Controller
    {
        [AllowAnonymous]
        public ActionResult ClientRegister()
        {
            return View();
        }

        [HttpPost, AllowAnonymous]
        public ActionResult ClientRegister(UserInfo user)
        {
            Provider provider = new Provider();
            user.AddBusiness = true;
            string errorMessage = string.Empty;
            UserManager.InsertClient(user, out errorMessage);

            if (string.IsNullOrEmpty(errorMessage))
            {
                if (Membership.ValidateUser(user.UserName, user.Password))
                {
                    FormsAuthentication.SetAuthCookie(user.UserName, false);
                    return RedirectToAction("BusinessInfo");
                }
                else
                    errorMessage = "Error validating account.";
            }

            ViewBag.ErrorMessage = errorMessage;
            return View(user);
        }

        [AllowAnonymous]
        public ActionResult ClientLogin()
        {
            return View();
        }

        [HttpPost, AllowAnonymous]
        public ActionResult ClientLogin(LoginModel model)
        {
            Provider provider = new Provider();

            if (ModelState.IsValid)
            {
                if (Membership.ValidateUser(model.UserName, model.Password))
                {
                    FormsAuthentication.SetAuthCookie(model.UserName, false);
                    return RedirectToAction("BusinessInfo");
                }

                ModelState.AddModelError("", "Invalid username and password.");
            }

            return View();
        }
        
        public ActionResult BusinessInfo()
        {
            ViewBag.typeList = WebTypeList();
            Business business = BusinessManager.BusinessGetByUser(User.Identity.Name);

            return View(business);
        }

        [HttpPost]
        public ActionResult BusinessInfo(Business business)
        {
            string errorMessage = string.Empty;
            business.user = UserManager.GetUserByName(User.Identity.Name);
            BusinessManager.BusinessUpdate(business, out errorMessage);

            if (string.IsNullOrEmpty(errorMessage))
                return RedirectToAction("Features", new { businessID = business.BusinessID});
            else
            {
                ViewBag.ErrorMessage = errorMessage;
                ViewBag.typeList = WebTypeList();
                return View(business);
            }
        }

        public ActionResult Features(int businessID)
        {
            List<FeatureRequested> model = FeatureManager.RequestedFeaturesByBusiness(businessID);
            return View(model);
        }

        [HttpPost]
        public ActionResult Features(List<FeatureRequested> features)
        {
            string errorMessage = string.Empty;
            FeatureManager.RequestFeatureUpdate(features, out errorMessage);

            TempData["MyRequests"] = features;
            return RedirectToAction("OrderResult");
        }

        public ActionResult OrderResult()
        {
            BusinessManager.SendAlertToWorkers();
            List<FeatureRequested> requestedFeatures = TempData["MyRequests"] as List<FeatureRequested>;
            return View(requestedFeatures);
        }

        private List<string> WebTypeList()
        {
            return new List<string>() { "A", "B", "C" };
        }
    }
}

202MobileServiceFour/202MobileServiceFour_Web/Controllers/DefaultController.cs
using _202MobileServiceFour_Core;
using _202MobileServiceFour_Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace _202MobileServiceFour_Web.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Directory()
        {
            return View();
        }
    }
}

202MobileServiceFour/202MobileServiceFour_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Assets/CSS/style.css">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        @Html.ActionLink("202 Mobile Service", "", "Default", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    @Html.ActionLink("Home", "", "Default", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("About Us", "", "Default", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Our Projects", "", "Default", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item active">
                    @Html.ActionLink("Your App", "ClientRegister", "Apps", new { area = "" }, new { @class = "nav-link" })
                </li>
            </ul>
        </div>
    </nav>

    <main role="main" class="main">
        @RenderBody()
    </main>
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="~/Assets/JS/inputmask.js"></script>
    <script src="~/Assets/JS/controlattributes.js"></script>
    <script src="~/Assets/JS/clientpword.js"></script>
</body>
</html>